from __future__ import annotations

import hashlib
import os
from datetime import date, datetime
from typing import Any, Dict, Optional

import pandas as pd
import streamlit as st
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

APP_NAME = "REALHYPE OS"
DEFAULT_DB_URL = "sqlite:///realhype_local.db"

# -----------------------------
# Visual
# -----------------------------
st.set_page_config(page_title="REALHYPE OS", page_icon="âš¡", layout="wide")

CUSTOM_CSS = """
<style>
:root {
  --rh-bg: #050608;
  --rh-card: #10141C;
  --rh-card-2: #151A24;
  --rh-gold: #D4AF37;
  --rh-cyan: #00E5FF;
  --rh-text: #F5F5F5;
  --rh-muted: #A7B0C0;
  --rh-danger: #FF4B4B;
  --rh-success: #30D158;
}
.block-container { padding-top: 1.4rem; }
[data-testid="stSidebar"] { background: linear-gradient(180deg, #07080C 0%, #10141C 100%); }
h1, h2, h3 { letter-spacing: .02em; }
.rh-hero {
  border: 1px solid rgba(212,175,55,.28);
  background: radial-gradient(circle at top left, rgba(0,229,255,.16), transparent 35%),
              linear-gradient(135deg, rgba(212,175,55,.12), rgba(16,20,28,.85));
  border-radius: 22px;
  padding: 22px 24px;
  box-shadow: 0 0 34px rgba(0,229,255,.07);
}
.rh-title { font-size: 32px; font-weight: 900; margin: 0; }
.rh-subtitle { color: var(--rh-muted); font-size: 14px; margin-top: 6px; }
.rh-chip {
  display: inline-block;
  padding: 5px 10px;
  border-radius: 999px;
  border: 1px solid rgba(0,229,255,.35);
  color: var(--rh-cyan);
  font-size: 12px;
  margin-right: 8px;
}
.rh-card {
  border: 1px solid rgba(255,255,255,.08);
  border-radius: 18px;
  padding: 18px;
  background: linear-gradient(180deg, rgba(21,26,36,.92), rgba(11,13,18,.95));
}
.rh-alert {
  border-left: 4px solid var(--rh-gold);
  padding: 12px 14px;
  border-radius: 12px;
  background: rgba(212,175,55,.08);
}
.small-muted { color: var(--rh-muted); font-size: 12px; }
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

# -----------------------------
# Database
# -----------------------------
def _normalize_db_url(raw_url: str) -> str:
    if raw_url.startswith("postgres://"):
        return raw_url.replace("postgres://", "postgresql+psycopg2://", 1)
    if raw_url.startswith("postgresql://"):
        return raw_url.replace("postgresql://", "postgresql+psycopg2://", 1)
    return raw_url


def get_db_url() -> str:
    try:
        raw_url = st.secrets["database"]["url"]
        if raw_url:
            return _normalize_db_url(raw_url)
    except Exception:
        pass
    return DEFAULT_DB_URL


@st.cache_resource
def get_engine(db_url: str) -> Engine:
    connect_args = {}
    if db_url.startswith("sqlite"):
        connect_args = {"check_same_thread": False}
    return create_engine(db_url, pool_pre_ping=True, connect_args=connect_args)


engine = get_engine(get_db_url())


def execute(sql: str, params: Optional[Dict[str, Any]] = None) -> None:
    with engine.begin() as conn:
        conn.execute(text(sql), params or {})


def query_df(sql: str, params: Optional[Dict[str, Any]] = None) -> pd.DataFrame:
    with engine.begin() as conn:
        return pd.read_sql_query(text(sql), conn, params=params or {})


def scalar(sql: str, params: Optional[Dict[str, Any]] = None, default: Any = 0) -> Any:
    with engine.begin() as conn:
        val = conn.execute(text(sql), params or {}).scalar()
        return default if val is None else val


def init_db() -> None:
    # SQL compatible with PostgreSQL and SQLite via SQLAlchemy text.
    execute("""
    CREATE TABLE IF NOT EXISTS products (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sku TEXT UNIQUE NOT NULL,
        name TEXT NOT NULL,
        category TEXT,
        quantity INTEGER NOT NULL DEFAULT 0,
        reorder_point INTEGER NOT NULL DEFAULT 1,
        cost_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
        sale_price_eur NUMERIC(12,2),
        active INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """ if not get_db_url().startswith("sqlite") else """
    CREATE TABLE IF NOT EXISTS products (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        sku TEXT UNIQUE NOT NULL,
        name TEXT NOT NULL,
        category TEXT,
        quantity INTEGER NOT NULL DEFAULT 0,
        reorder_point INTEGER NOT NULL DEFAULT 1,
        cost_brl REAL NOT NULL DEFAULT 0,
        sale_price_eur REAL,
        active INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS leads (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        contact TEXT,
        ig_handle TEXT,
        channel TEXT DEFAULT 'Instagram',
        interest TEXT,
        stage TEXT NOT NULL DEFAULT 'lead',
        owner TEXT,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """ if not get_db_url().startswith("sqlite") else """
    CREATE TABLE IF NOT EXISTS leads (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        contact TEXT,
        ig_handle TEXT,
        channel TEXT DEFAULT 'Instagram',
        interest TEXT,
        stage TEXT NOT NULL DEFAULT 'lead',
        owner TEXT,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS messages (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lead_id INTEGER NOT NULL,
        direction TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """ if not get_db_url().startswith("sqlite") else """
    CREATE TABLE IF NOT EXISTS messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        lead_id INTEGER NOT NULL,
        direction TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS orders (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lead_id INTEGER,
        status TEXT NOT NULL DEFAULT 'reservado',
        ctt_status TEXT NOT NULL DEFAULT 'pendente',
        confirmation_status TEXT NOT NULL DEFAULT 'pendente',
        total_eur NUMERIC(12,2) NOT NULL DEFAULT 0,
        total_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
        notes TEXT,
        created_by TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """ if not get_db_url().startswith("sqlite") else """
    CREATE TABLE IF NOT EXISTS orders (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        lead_id INTEGER,
        status TEXT NOT NULL DEFAULT 'reservado',
        ctt_status TEXT NOT NULL DEFAULT 'pendente',
        confirmation_status TEXT NOT NULL DEFAULT 'pendente',
        total_eur REAL NOT NULL DEFAULT 0,
        total_brl REAL NOT NULL DEFAULT 0,
        notes TEXT,
        created_by TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS order_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id INTEGER NOT NULL,
        product_id INTEGER NOT NULL,
        qty INTEGER NOT NULL,
        unit_price_eur NUMERIC(12,2) NOT NULL,
        unit_cost_brl NUMERIC(12,2) NOT NULL
    )
    """ if not get_db_url().startswith("sqlite") else """
    CREATE TABLE IF NOT EXISTS order_items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id INTEGER NOT NULL,
        product_id INTEGER NOT NULL,
        qty INTEGER NOT NULL,
        unit_price_eur REAL NOT NULL,
        unit_cost_brl REAL NOT NULL
    )
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS stock_movements (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id INTEGER NOT NULL,
        movement_type TEXT NOT NULL,
        qty INTEGER NOT NULL,
        reason TEXT,
        user_name TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """ if not get_db_url().startswith("sqlite") else """
    CREATE TABLE IF NOT EXISTS stock_movements (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        product_id INTEGER NOT NULL,
        movement_type TEXT NOT NULL,
        qty INTEGER NOT NULL,
        reason TEXT,
        user_name TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS expenses (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        expense_date DATE NOT NULL,
        category TEXT NOT NULL,
        amount_brl NUMERIC(12,2) NOT NULL,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """ if not get_db_url().startswith("sqlite") else """
    CREATE TABLE IF NOT EXISTS expenses (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        expense_date TEXT NOT NULL,
        category TEXT NOT NULL,
        amount_brl REAL NOT NULL,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """)

    execute("""
    CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    )
    """)
    execute("INSERT INTO settings (key, value) VALUES ('eur_brl', '5.80') ON CONFLICT (key) DO NOTHING" if not get_db_url().startswith("sqlite") else "INSERT OR IGNORE INTO settings (key, value) VALUES ('eur_brl', '5.80')")


if os.environ.get("REALHYPE_SKIP_DB_INIT") != "1":
    init_db()

# -----------------------------
# Auth
# -----------------------------
def get_users() -> Dict[str, Dict[str, str]]:
    try:
        users = st.secrets.get("users", {})
        if users:
            return {u: dict(v) for u, v in users.items()}
    except Exception:
        pass
    return {}


def login() -> bool:
    if st.session_state.get("auth"):
        return True
    st.markdown("""
    <div class="rh-hero">
      <p class="rh-title">REALHYPE OS</p>
      <p class="rh-subtitle">Painel operacional para stock, leads, vendas e decisÃµes crÃ­ticas.</p>
      <span class="rh-chip">Direct</span><span class="rh-chip">CTT</span><span class="rh-chip">Street Luxury</span>
    </div>
    """, unsafe_allow_html=True)
    st.write("")
    with st.form("login_form"):
        username = st.text_input("UsuÃ¡rio")
        password = st.text_input("Senha", type="password")
        ok = st.form_submit_button("Entrar")
    if ok:
        users = get_users()
        if username in users and password == users[username].get("password"):
            st.session_state["auth"] = True
            st.session_state["username"] = username
            st.session_state["role"] = users[username].get("role", "sdr")
            st.session_state["display_name"] = users[username].get("name", username)
            st.rerun()
        else:
            st.error("Login invÃ¡lido.")
    st.info("Configure os usuarios e senhas em Secrets antes de acessar o dashboard.")
    return False


if not login():
    st.stop()

ROLE = st.session_state.get("role", "sdr")
DISPLAY_NAME = st.session_state.get("display_name", "UsuÃ¡rio")
IS_PARTNER = ROLE == "partner"

# -----------------------------
# Helpers
# -----------------------------
def get_eur_rate() -> float:
    try:
        return float(scalar("SELECT value FROM settings WHERE key='eur_brl'", default="5.80"))
    except Exception:
        return 5.8


def money_eur(v: Any) -> str:
    return f"â‚¬ {float(v or 0):,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


def money_brl(v: Any) -> str:
    return f"R$ {float(v or 0):,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


def refresh_button():
    if st.button("Atualizar agora"):
        st.rerun()


# -----------------------------
# Data operations
# -----------------------------
def add_product(sku: str, name: str, category: str, qty: int, reorder_point: int, cost_brl: float, sale_price_eur: float):
    execute(
        """
        INSERT INTO products (sku, name, category, quantity, reorder_point, cost_brl, sale_price_eur)
        VALUES (:sku, :name, :category, :quantity, :reorder_point, :cost_brl, :sale_price_eur)
        ON CONFLICT (sku) DO UPDATE SET
            name = excluded.name,
            category = excluded.category,
            quantity = excluded.quantity,
            reorder_point = excluded.reorder_point,
            cost_brl = excluded.cost_brl,
            sale_price_eur = excluded.sale_price_eur,
            active = 1
        """ if not get_db_url().startswith("sqlite") else """
        INSERT INTO products (sku, name, category, quantity, reorder_point, cost_brl, sale_price_eur)
        VALUES (:sku, :name, :category, :quantity, :reorder_point, :cost_brl, :sale_price_eur)
        ON CONFLICT(sku) DO UPDATE SET
            name = excluded.name,
            category = excluded.category,
            quantity = excluded.quantity,
            reorder_point = excluded.reorder_point,
            cost_brl = excluded.cost_brl,
            sale_price_eur = excluded.sale_price_eur,
            active = 1
        """,
        {"sku": sku, "name": name, "category": category, "quantity": qty, "reorder_point": reorder_point, "cost_brl": cost_brl, "sale_price_eur": sale_price_eur},
    )


def add_lead(name: str, contact: str, ig_handle: str, channel: str, interest: str, stage: str, notes: str):
    execute(
        """
        INSERT INTO leads (name, contact, ig_handle, channel, interest, stage, owner, notes)
        VALUES (:name, :contact, :ig_handle, :channel, :interest, :stage, :owner, :notes)
        """,
        {"name": name, "contact": contact, "ig_handle": ig_handle, "channel": channel, "interest": interest, "stage": stage, "owner": DISPLAY_NAME, "notes": notes},
    )


def update_lead_stage(lead_id: int, stage: str):
    execute("UPDATE leads SET stage=:stage, updated_at=CURRENT_TIMESTAMP WHERE id=:id", {"stage": stage, "id": lead_id})


def add_message(lead_id: int, direction: str, content: str):
    execute("INSERT INTO messages (lead_id, direction, content) VALUES (:lead_id, :direction, :content)", {"lead_id": lead_id, "direction": direction, "content": content})


def create_order(lead_id: Optional[int], product_id: int, qty: int, unit_price_eur: float, status: str, confirmation_status: str, ctt_status: str, notes: str):
    rate = get_eur_rate()
    product = query_df("SELECT * FROM products WHERE id=:id", {"id": product_id})
    if product.empty:
        raise ValueError("Produto nÃ£o encontrado.")
    current_qty = int(product.iloc[0]["quantity"])
    if qty > current_qty:
        raise ValueError(f"Stock insuficiente. DisponÃ­vel: {current_qty}")
    unit_cost_brl = float(product.iloc[0]["cost_brl"] or 0)
    total_eur = unit_price_eur * qty
    total_brl = total_eur * rate
    with engine.begin() as conn:
        result = conn.execute(text("""
            INSERT INTO orders (lead_id, status, ctt_status, confirmation_status, total_eur, total_brl, notes, created_by)
            VALUES (:lead_id, :status, :ctt_status, :confirmation_status, :total_eur, :total_brl, :notes, :created_by)
        """), {"lead_id": lead_id, "status": status, "ctt_status": ctt_status, "confirmation_status": confirmation_status, "total_eur": total_eur, "total_brl": total_brl, "notes": notes, "created_by": DISPLAY_NAME})
        order_id = result.lastrowid
        if order_id is None:
            order_id = conn.execute(text("SELECT MAX(id) FROM orders")).scalar()
        conn.execute(text("""
            INSERT INTO order_items (order_id, product_id, qty, unit_price_eur, unit_cost_brl)
            VALUES (:order_id, :product_id, :qty, :unit_price_eur, :unit_cost_brl)
        """), {"order_id": order_id, "product_id": product_id, "qty": qty, "unit_price_eur": unit_price_eur, "unit_cost_brl": unit_cost_brl})
        conn.execute(text("UPDATE products SET quantity = quantity - :qty WHERE id=:product_id"), {"qty": qty, "product_id": product_id})
        conn.execute(text("""
            INSERT INTO stock_movements (product_id, movement_type, qty, reason, user_name)
            VALUES (:product_id, 'saida', :qty, :reason, :user_name)
        """), {"product_id": product_id, "qty": -qty, "reason": f"Pedido #{order_id}", "user_name": DISPLAY_NAME})
        if lead_id:
            conn.execute(text("UPDATE leads SET stage='cliente', updated_at=CURRENT_TIMESTAMP WHERE id=:lead_id"), {"lead_id": lead_id})
    return order_id

# -----------------------------
# Sidebar
# -----------------------------
with st.sidebar:
    st.markdown(f"### âš¡ {APP_NAME}")
    st.caption(f"Entrou como: **{DISPLAY_NAME}** Â· `{ROLE}`")
    page = st.radio("Menu", ["VisÃ£o Geral", "Leads & SDR", "Vendas", "Stock", "Financeiro", "ConfiguraÃ§Ãµes"])
    st.divider()
    if st.button("Sair"):
        st.session_state.clear()
        st.rerun()

# -----------------------------
# Header
# -----------------------------
st.markdown("""
<div class="rh-hero">
  <p class="rh-title">REALHYPE DASHBOARD</p>
  <p class="rh-subtitle">Painel em tempo real para sÃ³cios e SDR: stock, Direct, encomendas, CTT e margem.</p>
  <span class="rh-chip">Portugal</span><span class="rh-chip">Direct</span><span class="rh-chip">CTT</span><span class="rh-chip">PrÃ©-lanÃ§amento</span>
</div>
""", unsafe_allow_html=True)
st.write("")

# -----------------------------
# Pages
# -----------------------------
if page == "VisÃ£o Geral":
    refresh_button()
    col1, col2, col3, col4 = st.columns(4)
    leads_today = scalar("SELECT COUNT(*) FROM leads WHERE DATE(created_at)=CURRENT_DATE" if not get_db_url().startswith("sqlite") else "SELECT COUNT(*) FROM leads WHERE DATE(created_at)=DATE('now')")
    orders_count = scalar("SELECT COUNT(*) FROM orders")
    revenue_eur = scalar("SELECT COALESCE(SUM(total_eur),0) FROM orders")
    stock_units = scalar("SELECT COALESCE(SUM(quantity),0) FROM products WHERE active=1")
    col1.metric("Leads hoje", int(leads_today))
    col2.metric("Encomendas", int(orders_count))
    col3.metric("Receita", money_eur(revenue_eur))
    col4.metric("Unidades em stock", int(stock_units))

    st.subheader("Funil de Leads")
    funnel = query_df("SELECT stage, COUNT(*) AS total FROM leads GROUP BY stage ORDER BY total DESC")
    if funnel.empty:
        st.info("Ainda nÃ£o hÃ¡ leads registados.")
    else:
        st.bar_chart(funnel.set_index("stage"))
        st.dataframe(funnel, use_container_width=True, hide_index=True)

    st.subheader("Alertas de Baixo Stock")
    low = query_df("SELECT sku, name, quantity, reorder_point FROM products WHERE active=1 AND quantity <= reorder_point ORDER BY quantity ASC")
    if low.empty:
        st.success("Nenhum produto abaixo do ponto de reposiÃ§Ã£o.")
    else:
        st.warning("Produtos que precisam de atenÃ§Ã£o.")
        st.dataframe(low, use_container_width=True, hide_index=True)

elif page == "Leads & SDR":
    tab1, tab2, tab3 = st.tabs(["Cadastrar Lead", "Atualizar Funil", "Mensagens"])
    with tab1:
        with st.form("lead_form"):
            name = st.text_input("Nome do lead")
            ig = st.text_input("Instagram / @")
            contact = st.text_input("Contacto")
            channel = st.selectbox("Canal", ["Instagram", "WhatsApp", "Outro"])
            interest = st.selectbox("Interesse", ["CordÃ£o fino", "CordÃ£o mÃ©dio", "PresenÃ§a forte", "Pingente", "Presente", "NÃ£o definido"])
            stage = st.selectbox("EstÃ¡gio", ["lead", "prospect", "cliente", "perdido"])
            notes = st.text_area("Notas")
            if st.form_submit_button("Registrar lead"):
                if not name.strip():
                    st.error("Informe o nome do lead.")
                else:
                    add_lead(name, contact, ig, channel, interest, stage, notes)
                    st.success("Lead registado.")
                    st.rerun()
    with tab2:
        leads = query_df("SELECT id, name, ig_handle, stage, interest, created_at FROM leads ORDER BY id DESC")
        st.dataframe(leads, use_container_width=True, hide_index=True)
        if not leads.empty:
            lead_id = st.selectbox("Lead", leads["id"].tolist(), format_func=lambda x: f"#{x} Â· {leads[leads.id==x].iloc[0]['name']}")
            new_stage = st.selectbox("Novo estÃ¡gio", ["lead", "prospect", "cliente", "perdido"])
            if st.button("Atualizar estÃ¡gio"):
                update_lead_stage(int(lead_id), new_stage)
                st.success("EstÃ¡gio atualizado.")
                st.rerun()
    with tab3:
        leads = query_df("SELECT id, name FROM leads ORDER BY id DESC")
        if leads.empty:
            st.info("Cadastre um lead primeiro.")
        else:
            lead_id = st.selectbox("Lead da conversa", leads["id"].tolist(), format_func=lambda x: f"#{x} Â· {leads[leads.id==x].iloc[0]['name']}")
            with st.form("msg_form"):
                direction = st.selectbox("DireÃ§Ã£o", ["in", "out"], format_func=lambda x: "Cliente â†’ RealHype" if x == "in" else "RealHype â†’ Cliente")
                content = st.text_area("Mensagem")
                if st.form_submit_button("Guardar mensagem"):
                    if content.strip():
                        add_message(int(lead_id), direction, content)
                        st.success("Mensagem registada.")
                    else:
                        st.error("Digite a mensagem.")
            st.subheader("HistÃ³rico")
            msgs = query_df("SELECT direction, content, created_at FROM messages WHERE lead_id=:lead_id ORDER BY id DESC", {"lead_id": int(lead_id)})
            st.dataframe(msgs, use_container_width=True, hide_index=True)

elif page == "Vendas":
    st.subheader("Registrar Encomenda / Venda Confirmada")
    leads = query_df("SELECT id, name FROM leads ORDER BY id DESC")
    products = query_df("SELECT id, sku, name, quantity, sale_price_eur, cost_brl FROM products WHERE active=1 ORDER BY name")
    if products.empty:
        st.info("Cadastre produtos antes de registrar vendas.")
    else:
        with st.form("order_form"):
            lead_options = [None] + leads["id"].tolist() if not leads.empty else [None]
            lead_id = st.selectbox("Lead/Cliente", lead_options, format_func=lambda x: "Sem lead vinculado" if x is None else f"#{x} Â· {leads[leads.id==x].iloc[0]['name']}")
            product_id = st.selectbox("Produto", products["id"].tolist(), format_func=lambda x: f"{products[products.id==x].iloc[0]['sku']} Â· {products[products.id==x].iloc[0]['name']} Â· Stock {products[products.id==x].iloc[0]['quantity']}")
            selected = products[products.id == product_id].iloc[0]
            qty = st.number_input("Quantidade", min_value=1, step=1, value=1)
            default_price = float(selected["sale_price_eur"] or 0)
            unit_price = st.number_input("PreÃ§o unitÃ¡rio (â‚¬)", min_value=0.0, value=default_price, step=0.5)
            confirmation = st.selectbox("Dupla confirmaÃ§Ã£o CTT", ["pendente", "confirmado_texto", "confirmado_audio"])
            ctt = st.selectbox("Status CTT", ["pendente", "preparar", "enviado", "entregue", "devolvido"])
            status = st.selectbox("Status da venda", ["reservado", "confirmado", "cancelado"])
            notes = st.text_area("Notas / morada resumida / observaÃ§Ãµes")
            if st.form_submit_button("Registrar venda e dar saÃ­da no stock"):
                try:
                    order_id = create_order(None if lead_id is None else int(lead_id), int(product_id), int(qty), float(unit_price), status, confirmation, ctt, notes)
                    st.success(f"Venda registada. Pedido #{order_id}.")
                    st.rerun()
                except Exception as e:
                    st.error(str(e))
    st.subheader("Ãšltimas encomendas")
    orders = query_df("""
        SELECT o.id, l.name AS lead, o.status, o.confirmation_status, o.ctt_status, o.total_eur, o.total_brl, o.created_by, o.created_at
        FROM orders o
        LEFT JOIN leads l ON l.id = o.lead_id
        ORDER BY o.id DESC
        LIMIT 50
    """)
    st.dataframe(orders, use_container_width=True, hide_index=True)

elif page == "Stock":
    tab1, tab2 = st.tabs(["Stock Atual", "Cadastrar/Atualizar Produto"])
    with tab1:
        products = query_df("SELECT sku, name, category, quantity, reorder_point, cost_brl, sale_price_eur, active FROM products ORDER BY name")
        st.dataframe(products, use_container_width=True, hide_index=True)
    with tab2:
        if not IS_PARTNER and ROLE != "sdr":
            st.error("Sem permissÃ£o.")
        else:
            with st.form("product_form"):
                sku = st.text_input("SKU", placeholder="ex: GRUMET3MM")
                name = st.text_input("Nome do produto", placeholder="ex: Grumet 3MM")
                category = st.selectbox("Categoria", ["CordÃµes Finos", "CordÃµes MÃ©dios", "PresenÃ§a Forte", "CordÃµes Grossos", "Pingentes", "Outro"])
                qty = st.number_input("Quantidade", min_value=0, step=1, value=0)
                reorder = st.number_input("Ponto de reposiÃ§Ã£o", min_value=0, step=1, value=1)
                cost = st.number_input("Custo unitÃ¡rio (BRL)", min_value=0.0, value=0.0, step=1.0)
                price = st.number_input("PreÃ§o venda (â‚¬)", min_value=0.0, value=0.0, step=0.5)
                if st.form_submit_button("Guardar produto"):
                    if sku.strip() and name.strip():
                        add_product(sku.strip().upper(), name.strip(), category, int(qty), int(reorder), float(cost), float(price))
                        st.success("Produto guardado.")
                        st.rerun()
                    else:
                        st.error("SKU e nome sÃ£o obrigatÃ³rios.")

elif page == "Financeiro":
    if not IS_PARTNER:
        st.warning("Ãrea restrita aos sÃ³cios.")
        st.stop()
    st.subheader("Resumo Financeiro")
    revenue_eur = scalar("SELECT COALESCE(SUM(total_eur),0) FROM orders")
    revenue_brl = scalar("SELECT COALESCE(SUM(total_brl),0) FROM orders")
    cost_brl = scalar("SELECT COALESCE(SUM(oi.qty * oi.unit_cost_brl),0) FROM order_items oi")
    expenses_brl = scalar("SELECT COALESCE(SUM(amount_brl),0) FROM expenses")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Receita EUR", money_eur(revenue_eur))
    col2.metric("Receita BRL", money_brl(revenue_brl))
    col3.metric("CMV BRL", money_brl(cost_brl))
    col4.metric("Lucro estimado BRL", money_brl(float(revenue_brl) - float(cost_brl) - float(expenses_brl)))

    st.subheader("LanÃ§ar despesa")
    with st.form("expense_form"):
        exp_date = st.date_input("Data", value=date.today())
        category = st.selectbox("Categoria", ["Ads", "CTT", "Embalagem", "Fornecedor", "Ferramentas", "Outro"])
        amount = st.number_input("Valor (BRL)", min_value=0.0, step=1.0)
        notes = st.text_area("Notas")
        if st.form_submit_button("Guardar despesa"):
            execute("INSERT INTO expenses (expense_date, category, amount_brl, notes) VALUES (:d, :c, :a, :n)", {"d": str(exp_date), "c": category, "a": float(amount), "n": notes})
            st.success("Despesa registada.")
            st.rerun()
    expenses = query_df("SELECT expense_date, category, amount_brl, notes, created_at FROM expenses ORDER BY id DESC LIMIT 50")
    st.dataframe(expenses, use_container_width=True, hide_index=True)

elif page == "ConfiguraÃ§Ãµes":
    if not IS_PARTNER:
        st.warning("Ãrea restrita aos sÃ³cios.")
        st.stop()
    st.subheader("ConfiguraÃ§Ãµes")
    current_rate = get_eur_rate()
    rate = st.number_input("CotaÃ§Ã£o EUR â†’ BRL", min_value=0.0, value=float(current_rate), step=0.01)
    if st.button("Salvar cotaÃ§Ã£o"):
        execute("UPDATE settings SET value=:v WHERE key='eur_brl'", {"v": str(rate)})
        st.success("CotaÃ§Ã£o atualizada.")
        st.rerun()
    st.markdown("""
    <div class="rh-alert">
      <b>SeguranÃ§a:</b> no Streamlit Cloud, configure usuÃ¡rios e senhas em <code>Secrets</code>.
      NÃ£o publique senhas no GitHub.
    </div>
    """, unsafe_allow_html=True)
