-- REALHYPE OS MVP schema for PostgreSQL/Neon.
-- The app creates these tables automatically on first run.

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    quantity INTEGER NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 1,
    cost_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
    sale_price_eur NUMERIC(12,2),
    currency TEXT DEFAULT 'EUR',
    description TEXT,
    tags TEXT,
    warranty_notes TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT,
    ig_handle TEXT,
    channel TEXT DEFAULT 'Instagram',
    interest TEXT,
    stage TEXT NOT NULL DEFAULT 'lead',
    owner TEXT,
    notes TEXT,
    temperature TEXT DEFAULT 'morno',
    urgency TEXT DEFAULT 'normal',
    next_action TEXT,
    next_action_at TIMESTAMP,
    last_interaction_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INTEGER,
    status TEXT NOT NULL DEFAULT 'reservado',
    ctt_status TEXT NOT NULL DEFAULT 'pendente',
    confirmation_status TEXT NOT NULL DEFAULT 'pendente',
    channel TEXT DEFAULT 'Instagram',
    text_confirmed INTEGER DEFAULT 0,
    address_validated INTEGER DEFAULT 0,
    phone_validated INTEGER DEFAULT 0,
    pickup_deadline DATE,
    returned INTEGER DEFAULT 0,
    return_reason TEXT,
    total_eur NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_by TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    qty INTEGER NOT NULL,
    unit_price_eur NUMERIC(12,2) NOT NULL,
    unit_cost_brl NUMERIC(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    movement_type TEXT NOT NULL,
    qty INTEGER NOT NULL,
    reason TEXT,
    user_name TEXT,
    notes TEXT,
    movement_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date DATE NOT NULL,
    category TEXT NOT NULL,
    amount_brl NUMERIC(12,2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS campaign_metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign TEXT NOT NULL,
    creative TEXT,
    channel TEXT,
    investment_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
    messages_received INTEGER NOT NULL DEFAULT 0,
    leads_count INTEGER NOT NULL DEFAULT 0,
    sales_count INTEGER NOT NULL DEFAULT 0,
    revenue_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes TEXT,
    metric_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor TEXT,
    role TEXT,
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    before_data TEXT,
    after_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO settings (key, value)
VALUES ('eur_brl', '5.80')
ON CONFLICT (key) DO NOTHING;
