-- REALHYPE OS MVP schema for PostgreSQL/Neon.
-- The app creates these tables automatically on first run.

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    quantity INTEGER NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 1,
    cost_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
    sale_price_eur NUMERIC(12,2),
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT,
    ig_handle TEXT,
    channel TEXT DEFAULT 'Instagram',
    interest TEXT,
    stage TEXT NOT NULL DEFAULT 'lead',
    owner TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INTEGER,
    status TEXT NOT NULL DEFAULT 'reservado',
    ctt_status TEXT NOT NULL DEFAULT 'pendente',
    confirmation_status TEXT NOT NULL DEFAULT 'pendente',
    total_eur NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_brl NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_by TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    qty INTEGER NOT NULL,
    unit_price_eur NUMERIC(12,2) NOT NULL,
    unit_cost_brl NUMERIC(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    movement_type TEXT NOT NULL,
    qty INTEGER NOT NULL,
    reason TEXT,
    user_name TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date DATE NOT NULL,
    category TEXT NOT NULL,
    amount_brl NUMERIC(12,2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

INSERT INTO settings (key, value)
VALUES ('eur_brl', '5.80')
ON CONFLICT (key) DO NOTHING;
